### ISSUE TITLE
Adding an item to an empty list causes an error

### ISSUE THREAD

**Issue by andrew-codechimp** [andrew-codechimp/HA-Mealie#13]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/HA-Mealie/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Adding an item to an empty list causes an error

### Reproduction steps

Add an item to an empty list

### Debug logs

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/todo/__init__.py", line 463, in _async_add_todo_item
    await entity.async_create_todo_item(
  File "/config/custom_components/mealie/todo.py", line 128, in async_create_todo_item
    self.coordinator.shopping_list_items[self._shopping_list_id][-1].get(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by andrew-codechimp** [comment]
Fixed in 1.1.3
